project:
  type: website
  output-dir: docs

website:
  favicon: favicon.png
  navbar:
    logo: logo.png
    background: dark
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Calendar"
        href: calendar.qmd
      - sidebar:syllabus
      - text: "Project"
        href: project/project.qmd
      - text: "Datasets"
        href: project/data.qmd
      - text: "Moodle Page"
        href: https://courses.furman.edu/course/view.php?id=18728
      - text: "Office Hours"
        href: syllabus/appointment.md
      - text: "TA"
        href: ta.qmd
  sidebar:
    - id: syllabus
      title: "Syllabus"
      background: light
      collapse-level: 2
      contents:
        - syllabus/about.qmd
        - syllabus/grading.qmd
        - syllabus/academic_success.md
        - syllabus/textbook.md
        - syllabus/integrity.md
        - syllabus/mental_health.md
        - syllabus/accomodations.md
        - syllabus/title_9.md
    - id: content
      background: "#2d2d2d"
      style: "floating"
      search: true
      contents:
        - text: "Home"
          href: index.qmd
        - text: "Introduction"
          href: intro.qmd
        - section: 
          href: pandas/linalg.ipynb
          contents:
            - section:
              href: pandas/preliminaries.ipynb
              contents: 
                - pandas/read_data.ipynb
                - pandas/view_data.ipynb
                - pandas/write_data.ipynb
                - encoding/types.ipynb
            - section:
              href: pandas/select_filter.ipynb
              contents: 
                - pandas/extraction.ipynb
                - pandas/selection.ipynb
                - pandas/filtering.ipynb
                - pandas/dropping.ipynb
            - section:
              href: pandas/wrangling.ipynb
              contents: 
                - pandas/apply.ipynb
                - pandas/concat_merge.ipynb
            - section:
              href: encoding/encoding.ipynb
              contents:
                - encoding/text.ipynb
                - encoding/network.ipynb
                - encoding/sound.ipynb
                - encoding/images.ipynb
                - encoding/spatial.ipynb
                - encoding/time.ipynb
            - section:
              href: linearalgebra/vectors.ipynb
              contents:
                - linearalgebra/matrices.ipynb
                - linearalgebra/nearestneighbor.qmd
        - section:
          href: stats/stats.ipynb
          contents:
            - stats/summary.ipynb
            - stats/distributions.ipynb
            - section:
              href: pandas/aggregation.ipynb
              contents: 
                - pandas/grouping.ipynb
                - pandas/pivot.ipynb
        - section:
          href: probability/probability.ipynb
          contents:
            - href: probability/joint_prob.ipynb
            - href: probability/conditional_prob.ipynb
            - href: probability/naivebayes.ipynb
        #   contents:
        #     - probability/bayestheorem.qmd
        - section:
          href: calculus/calculus0.qmd
          contents:
            - calculus/52_differential.ipynb
            - calculus/41_classification.ipynb
            - calculus/em.ipynb
            - calculus/gradientdescent.ipynb

format:
  html:
    theme:
      - darkly
      - custom.scss
    css: style.css
    toc: true
    # monobackgroundcolor: "#CCCCFF"
    monobackgroundcolor: "black"
    highlight-style: monokai #atom-one, github, dracula, monokai
    anchor-sections: true
    smooth-scroll: true
    # number-sections: true


